name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          php_extensions: gd mysqli ldap http zip
      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          php_extensions: gd mysqli ldap http zip
  semrel:
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: byteshard/templates/semrel@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}